apps/accounts/urls.py
from django.urls import path
from . views import index
from . views import register
from . views import login
from .views import statistics

app_name = 'accounts'
urlpatterns = [
    path('', index, name='index'),
    path('register', register, name='register'),
    path('login', login, name='login'),
    path('statistics', statistics, name='statistics'),
]

apps/cart/urls.py
from django.urls import path
from . views import index

app_name = 'cart'
urlpatterns = [
    path('', index, name='index'),
]

apps/home/urls.py
from django.urls import path
from . views import index

app_name = 'home'
urlpatterns = [
    path('', index, name='index'),
]

apps/orders/urls.py
from django.urls import path
from . views import index

app_name = 'orders'
urlpatterns = [
    path('', index, name='index'),
]

apps/products/urls.py
from django.urls import path

apps/support/urls.py
from django.urls import path
from . views import index

app_name = 'support'
urlpatterns = [
    path('', index, name='support'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('perfil/', include('apps.accounts.urls')),
    path('statistics/', include('apps.accounts.urls')),
    path('produtos/', include('apps.products.urls')),
    path('carrinho/', include('apps.cart.urls')),
    path('orders/', include('apps.orders.urls')),
    path('suporte/', include('apps.support.urls')),
]

home/urls.py
from django.urls import path
from . views import index

urlpatterns = [
    path('', index, name='home'),
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now

class Users(models.Model):
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    birthdate = models.CharField(max_length=8)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=255)
    password = models.CharField(max_length=100)

def __str__(self):
    return self.username

class DailyAccess(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    ip_address = models.GenericIPAddressField()
    data = models.DateField(default=now)

    class Meta:
        unique_together = ('username', 'ip_address', 'data')

apps/cart/models.py
from django.db import models

# Create your models here.

apps/home/models.py
from django.db import models

apps/orders/models.py
from django.db import models

# Create your models here.

apps/products/models.py
from django.db import models

# Create your models here.

apps/support/models.py
from django.db import models

# Create your models here.

apps/accounts/views.py
from django.shortcuts import render
from django.utils.timezone import now
from .models import DailyAccess
from .models import Users


def index(request):
    if request.user.is_authenticated:
        return render(request, 'accounts/index.html')
    return render(request, 'accounts/login.html')

def register(request):
    if request.method == 'GET':
        return render(request, 'accounts/register.html')
    elif request.method == 'POST':
        return render(request, 'accounts/login.html')

def login(request):
    if request.method == 'GET':
        return render(request, 'accounts/login.html')
    elif request.method == 'POST':
        return render(request, 'accounts/index.html')

def statistics(request):
    today = now().date()
    total_acessos = DailyAccess.objects.filter(data=today).count()

    return render(request, 'accounts/statistics.html', {'total_acessos': total_acessos})

apps/cart/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'cart/index.html')

apps/home/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html')

apps/orders/views.py
from django.shortcuts import render

# Create your views here.

apps/products/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'products/index.html')

apps/support/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'support/index.html')

apps/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Perfil</h1>
{% endblock content %}

apps/accounts/templates/accounts/login.html
login

apps/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block 'section' %}
    <h2>Registrar</h2>
    <form action="/submit_registration" method="post">{% csrf_token %}
        <label for="firstname">Nome:</label><br>
        <input type="text" id="firstname" name="firstname" required><br><br>
        
        <label for="lastname">Sobrenome:</label><br>
        <input type="text" id="lastname" name="lastname" required><br><br>
        
        <label for="birthdate">Data de Nascimento:</label><br>
        <input type="date" id="birthdate" name="birthdate" required><br><br>
        
        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" required><br><br>
        
        <label for="phone">Telefone:</label><br>
        <input type="tel" id="phone" name="phone"><br><br>
        
        <label for="password">Senha:</label><br>
        <input type="password" id="password" name="password" required><br><br>
        
        <input type="submit" value="Registrar">
    </form>

{% endblock 'section' %}

apps/accounts/templates/accounts/statistics.html
{% load static %}

{% block content %}
<h1>Acessos de Hoje</h1>
<p>Total de acessos únicos: {{ total_acessos }}</p>
{% endblock content %}

apps/cart/templates/cart/index.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock content %}

apps/home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
{% endblock content %}

apps/orders/templates/orders/index.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock content %}

apps/products/templates/products/index.html
{% extends 'base.html' %}

{% block content %}
    
{% endblock content %}

apps/support/templates/support/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>suporte</h1>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="author" content="Abrell">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static '/img/aiko.svg' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css'  %}">
    <title>Aiko</title>
</head>

<body>
    <header>
        <h1>Aiko</h1>
        <nav>
            <ul>
                <li><a href="{% url 'home:index' %}">Inicio</a></li>
                <li><a href="{% url 'support:support' %}">Suporte</a></li>
                <li><a href="{% url 'cart:index' %}">Carrinho</a></li>
                <li><a href="{% url 'accounts:index' %}">Perfil</a></li>
                <li><a href="{% url 'accounts:statistics' %}">Acessos</a></li>
            </ul>
        </nav>
    </header>
    <main>{% block 'section' %}{% endblock 'section' %}</main>
    <noscript>Você precisa habilitar o JavaScript</noscript>
</body>

</html>